### ISSUE TITLE
Can't get Docker container to run

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#101]
When I run `./script/bootstrap` I get the error `Could not find rake-11.1.2 in any of the sources
Run 'bundle install' to install missing gems.`. 

Which is weird because `sudo bundle show | grep rake` lists `* rake (11.1.2)`. I already tried reinstalling and updating, `rbenv rehash` doesn't fix this either, neither does `bundle install`. `bundle check` returns `The Gemfile's dependencies are satisfied`. 

Do you have an idea what's the problem here? It kinda sucks since I can't continue working.

**Comment by davidpdrsn** [comment]
I see why. I made a change to the setup and forgot to update the script. d95c20b fixes it. Please try again :)

It was because `bundle install` wasn't run as part of building the container and `bundle show` shows you local gems, not the gems installed in the container.

**Comment by ghost** [comment]
Very nice. I will try it out after work :).

Another thing: Would I need a new version of the files with the API keys and such? You've mailed me that in the past and I see you have added some new services.

Edit: Oops, wrong account :D

**Comment by davidpdrsn** [comment]
I posted the credentials on slack. Let me know if something doesn't work.

**Comment by davidpdrsn** [comment]
Seems you have gotten it to work.
