### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#114]
We should consider printing some stickers for CC! 💯 💯

**Comment by davidpdrsn** [comment]
Oh yeah thats a great idea! I want one for my laptop as well 😜

**Comment by bendobos** [comment]
Awesome! We could get 1000 "outdoor" Stickers, 5,5 x 8,5 cm, on white foil for 27,98€. 2500 would be 41,75€. We should maybe just split the price?

Are we both happy with the current logo design or should I see if I can come up with something else? If we like it, I could throw something together to get it printed.

<img width="393" alt="bildschirmfoto 2016-05-22 um 10 37 22" src="https://cloud.githubusercontent.com/assets/3368356/15453133/3a6a357e-2009-11e6-9f95-7e3642a7d1d6.png">

**Comment by davidpdrsn** [comment]
I think 1000 is more than enough and yeah lets split the cost 😄 I remember there were stickers at cardistry con last year so there might be again this year and in any case we can just spread them throughout the place.

I'm fine with the logo as it is right now but if you have time to play around with something go right ahead.

**Comment by bendobos** [comment]
I will get this going in the next few days so there's enough time before CC for them to finish up printing.

**Comment by davidpdrsn** [comment]
Awesome! I already know where I wanna put it on my laptop 😊

https://www.instagram.com/p/BAKnamurf1w/?taken-by=davidpdrsn

**Comment by bendobos** [comment]
I will make sure to mail you some in advance then ;).
