### ISSUE TITLE
Logo 404s

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#116]

**Comment by lpalmes** [comment]
Do you mean this logo in the header bar?
![screen shot 2016-06-15 at 2 56 25 pm](https://cloud.githubusercontent.com/assets/5133531/16091310/788f18b6-3309-11e6-93f0-04b3f103e68c.png)

**Comment by davidpdrsn** [comment]
Yeah when I run the app locally that logo 404s for some reason.

**Comment by bendobos** [comment]
Fixed in a0ffd7a7aefa24781072761fd936f2ef2896b4cf

**Comment by lpalmes** [comment]
Yeah i did get it too. Small path issue

```
- = link_to image_tag("logo2.svg", :class => "main-logo"), root_path
+ = link_to image_tag("logo.svg", :class => "main-logo"), root_path
```

Would't be awesome if you could get some sort of color here

**Comment by davidpdrsn** [comment]
@bendobos great! I'll close this then.

**Comment by bendobos** [comment]
I think `logo2.svg` once was the logo without the beta tag. Can't quite remember anymore.
