### ISSUE TITLE
Setup a development flag that skips production services

### ISSUE THREAD

**Issue by lpalmes** [davidpdrsn/CardistryIO#120]
Tried to startup some containers and i have this issue where i don't have the skylight authentication key.

```
/box/gems/skylight-0.10.3/lib/skylight/config.rb:215:in `load': could not load config file; msg=key not found: "SKYLIGHT_AUTHENTICATION" (Skylight::ConfigError)
    from /box/gems/skylight-0.10.3/lib/skylight/railtie.rb:74:in `load_skylight_config'
    from /box/gems/skylight-0.10.3/lib/skylight/railtie.rb:24:in `block in <class:Railtie>'
    from /box/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
```

I would suggest to add a development flag so that this services that are useful in production are skipped. Or the other way around, a production flag, given that we probably work in development more than deploys.

@davidpdrsn , if you could help me around this issue it would be really helpful. I'm not familiar right now how skylight works, but i'm going to take a look at it.

**Comment by davidpdrsn** [comment]
Sorry for the late reply.

This happens because the file `config/application.yml` isn't checked in to Git. We use it to store secrets such as the api key to skylight.

The easier fix would be to generate a file with dummy values during `script/bootstrap`. I'll look into that 😄

**Comment by davidpdrsn** [comment]
I've opened a [new issue](https://github.com/davidpdrsn/CardistryIO/issues/123) for adding the feature.

Hopefully I'll get time to fix it this weekend.

**Comment by davidpdrsn** [comment]
This should be fixed now https://github.com/davidpdrsn/CardistryIO/pull/131
