### ISSUE TITLE
Use docker networking instead of linking

### ISSUE THREAD

**Issue by lpalmes** [davidpdrsn/CardistryIO#122]
Docker announced in 1.9 that container linking will be deprecated in favor of networking.
I could probably migrate to networking.
If someone is unfamiliar with networking there is this docker guide: [Understand Docker container networks](https://docs.docker.com/engine/userguide/networking/dockernetworks/)

**Comment by davidpdrsn** [comment]
I'm not familiar with docker networking but you're very welcome to take a crack at it 😄

**Comment by davidpdrsn** [comment]
This was fixed by https://github.com/davidpdrsn/CardistryIO/pull/150
