### ISSUE TITLE
Don't create issues for local dev errors

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#127]
Such as https://github.com/davidpdrsn/CardistryIO/issues/126

**Comment by davidpdrsn** [comment]
This should be fixed now.

**Comment by davidpdrsn** [comment]
Turns out not to be fixed yet

<img width="645" alt="screen shot 2016-06-21 at 07 02 58" src="https://cloud.githubusercontent.com/assets/718941/16218456/384cb320-377e-11e6-889d-17620a0bb0ce.png">

**Comment by bendobos** [comment]
It would be nice to turn that off 👍 .

**Comment by davidpdrsn** [comment]
727cdfe should fix it.

@bendobos you'll have to rebase master onto whatever branches you may have.

**Comment by bendobos** [comment]
Yep, will do when I get home from work.
