### ISSUE TITLE
Data for activities on feed

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#129]
Maybe I was just too tired last night but I couldn't figure out how to get some of the data we need for activities on the feed.

I'll just list what is needed and maybe someone can comment on if it's already there and how to get it or if it is yet to be implemented.
- User Name of the owner of the activity
- Title and description
- Video Thumbnail

**Comment by davidpdrsn** [comment]
- User Name of the owner of the activity: `activity.user.username`
- Title and description: `activity.subject.name` or `activity.subject.description`. Remember that subjects can be either videos or moves.
- Video Thumbnail: Wow totally forgotten about video thumbnails. Have to look into that.

**Comment by davidpdrsn** [comment]
I'll close this. Feel free to reopen if you have more questions :)

**Comment by bendobos** [comment]
Are there any helpers available to format `activity.created_at` into something more readable?

**Comment by davidpdrsn** [comment]
Yep. You can call `activity.created_at.strftime(format)`. You can find
documentation and examples [here](http://apidock.com/ruby/Time/strftime).

**Comment by bendobos** [comment]
I think it'd be really cool if we had it like instagram:
- `2 minutes ago`
- `5 hours ago`
- `4 days ago`
- `20 days ago`
- if it is older than one month, display the date it was posted add. Leave out the year if it was posted in the current year

As far as I was able to find out, this is not easily possible with `strftime`.

**Comment by bendobos** [comment]
Ah! I just found out about `time_ago_in_words` and `distance_of_time_in_words`. Living in an Angular world, having stuff like this built-in keeps surprising me! 👯

**Comment by davidpdrsn** [comment]
💥 Angular 🔫
