### ISSUE TITLE
Video thumbnails

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#130]
We have to somehow get thumbnails for videos. Currently the videos are just embedded from youtube, vimeo or instagram. Have to handle all cases.

**Comment by davidpdrsn** [comment]
I have started working on this but hit a bit of a [road block](https://github.com/davidpdrsn/CardistryIO/issues/142).

**Comment by bendobos** [comment]
Any news on this?

**Comment by davidpdrsn** [comment]
No 😞 Haven't had time to work on it.
