### ISSUE TITLE
Make project more friendly to new contributors

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#140]
Write about the following in either the wiki or markdown files in the repo:
- [x] Introduction to the project, "what the hell is this thing?"
- [x] Contributing guidelines
- [x] Mention of "Low hanging fruit" issue label
- [x] Code of conduct
- [x] Review readme
- [x] Who are the core contributors and how can you reach them?

@lpalmes @corroded Any other things you think would be help new contributors?

**Comment by davidpdrsn** [comment]
I suggest we use [this template](http://todogroup.org/opencodeofconduct/) as our initial code of conduct. @bendobos thoughts?

**Comment by corroded** [comment]
Looks good! Architecture diagram maybe? Or should that be private?

**Comment by davidpdrsn** [comment]
Good idea but so far it's just a standard Rails app. The architecture just follows Rails conventions. So maybe that's not necessary.

**Comment by davidpdrsn** [comment]
We now have
- [A nicer readme](https://github.com/davidpdrsn/CardistryIO/blob/master/README.md)
- [Contributing guidelines](https://github.com/davidpdrsn/CardistryIO/blob/master/CONTRIBUTING.md)
- [Code of conduct](https://github.com/davidpdrsn/CardistryIO/blob/master/CODE_OF_CONDUCT.md)
- [A list of core contributors](https://github.com/davidpdrsn/CardistryIO/wiki/Core-Team)

Please let me know if you have suggestions and don't hesitate to submit pull requests :smile:

**Comment by lpalmes** [comment]
Wow, i missed this issue notification, i wonder how that happend.
It looks like an nice improvement for newcomers, if anything comes to mind i let you know.
