### ISSUE TITLE
List a user's media on the profile page

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#141]
If you take a look at the design, I'm planning on listing Videos/Moves/Ideas on a user's profile page.

Is it possible right now to access this data?

**Comment by davidpdrsn** [comment]
Indeed it is:
- Videos: `@user.videos`
- Moves: `@user.moves`
- Ideas: Ideas are just moves where the `idea` column is `true`. So to get all moves where `idea` is true you do `@user.moves.where(idea: true)`. You can use the same snippet to get moves where idea is false.

**Comment by corroded** [comment]
Actually I just checked and you can do `@user.moves.ideas` for ideas and `@user.moves.finished` for moves that aren't ideas. 

@davidpdrsn I can quickly make a PR to add those ivars to the controller for @bendobos to use if you like?

**Comment by davidpdrsn** [comment]
@corroded I think going through `@user` is more clear. Having more than once ivar in the view is usually not a good idea. It is also one of [Sandy Metz' rules](https://robots.thoughtbot.com/sandi-metz-rules-for-developers)
