### ISSUE TITLE
Most popular videos and users

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#144]
If you take a look at the styling-feed branch, I am planning on giving users a selection of the best videos so they have an idea where to start.

It would be cool if we could prepare something to display the top-3/top-10 of both videos and users. I can also use this for the landing page.

For release, we could have our testers vote on videos or we just hardcode some until there's enough data to show the best stuff dynamically.

**Comment by davidpdrsn** [comment]
I guess we could take it a bit further and make it possible for admins to "feature" videos. That way users can both see what we think is really great and deserves attention, or use the current sorting feature to find the highest rated/viewed videos.

It would also give us a bit more control over what appears in that part of people feed and on the front page.

What do you think?

**Comment by davidpdrsn** [comment]
We have been able to feature videos for some time now, currently only visible to admins however.

I'll close this and soon enable featured videos for everyone.

I imagine we can highlight the featured videos on the landing page.
