### ISSUE TITLE
Limit character count for user bio

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#148]
We should limit how much you can put there.

I was thinking something like 140 characters so it is like a tweet?
Or 156 so it is a multiple of 52? 💨

**Comment by bendobos** [comment]
Actually, around 100 characters would be best in my opinion. That's enough space for the user to put one or two short sentences and maybe a link.

**Comment by davidpdrsn** [comment]
Good idea. I added in 9f98dce.

I set the maximum to 100 as you suggested and if you wanna get the limit in a view or something you can with `User::BIOGRAPHY_MAX_LENGTH`. Getting it that way is a bit safer than hardcoding 100.
