### ISSUE TITLE
Add KSS 

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#162]
I'd like to make a style guide to make it easier for people to contribute and also use the chance to refactor the SCSS a bit to make it more modular.
Adding KSS should be pretty easy, as documented here http://warpspire.com/kss/styleguides/.

**Comment by davidpdrsn** [comment]
Yeah sure lets go for it.

**Comment by bendobos** [comment]
I have added some KSS comments. An HTML styleguide should be generated locally.
As soon as I have documented everything I will host the style guide it in a seperate repo. This is not my main priority right now though.
