### ISSUE TITLE
Feature Request - Underground Video Trading

### ISSUE THREAD

**Issue by EliotSlevin** [davidpdrsn/CardistryIO#167]
So me and Spencer Clark were remembering how great underground videos were. The best part of it however, was the trading. "I'll swap you one daren for one jonas". They were like a weird currency. 

I'd like to make a request for video trading to be a feature, and for videos to be treated as 'inventory'. Bring back cardistry currency.

**Comment by bendobos** [comment]
We are planning to have an option that makes a video private. Only people with the link can then see the video. You could then trade a link for another link.
Is that what you have in mind or are you proposing a more sophisticated system?

**Comment by EliotSlevin** [comment]
I was imagining something more elaborate, closer to bitcoins. 

I'd also like to make it clear I was talking shit haha, it would be a terrible feature.

**Comment by davidpdrsn** [comment]
Haha yes I agree it would be a terrible feature.
