### ISSUE TITLE
Store the currently selected filter option somewhere

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#168]
<img width="707" alt="screen shot 2016-08-11 at 20 17 41" src="https://cloud.githubusercontent.com/assets/3368356/17599726/b4356b62-6000-11e6-9a92-bacefcc19c66.png">

This is how I have redesigned the selects for the filtering options. After submitting the form, the first value is selected again, however the previously selected option should be highlighted.

It's important since I have gotten rid of the labels and the submit button.

**Comment by davidpdrsn** [comment]
This works now, but the options aren't maintained when paging. I'll get on that next.

**Comment by davidpdrsn** [comment]
Done! 💣
