### ISSUE TITLE
Ratings get cut off

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#176]
Might be a feature that you cannot rate more than 2 out of 5, but I think we should fix it none the less.

![screen shot 2016-08-27 at 18 42 30](https://cloud.githubusercontent.com/assets/718941/18028727/18be621e-6c86-11e6-8791-84820987d7c8.png)

**Comment by bendobos** [comment]
I have actually not done anything with this yet. This will be the next thing I do.

**Comment by davidpdrsn** [comment]
Awesome 😊

**Comment by davidpdrsn** [comment]
Fixed by https://github.com/davidpdrsn/CardistryIO/pull/182
