### ISSUE TITLE
Phone/tablet bug

### ISSUE THREAD

**Issue by ItsBen321** [davidpdrsn/CardistryIO#179]
I'm using android, rating a video is impossible using devices like this, see the image added to it.
![screenshot_2016-08-27-19-50-24](https://cloud.githubusercontent.com/assets/21281708/18029141/19694d3c-6c90-11e6-857a-d5c68c0d2f86.png)

**Comment by davidpdrsn** [comment]
Hey and welcome to the project.

We are already aware of this issue https://github.com/davidpdrsn/CardistryIO/issues/176
Should have a fix for it soon.

**Comment by davidpdrsn** [comment]
This has now been fixed :)
