### ISSUE TITLE
Unapproved videos are shown on profile page

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#197]

**Comment by davidpdrsn** [comment]
Sure? [mattbeaudouin](http://cardistry.io/users/109-mattbeaudouin) has an unapproved video called "Erdnase Got Around" which I don't see on his profile.

![screen shot 2016-08-29 at 17 24 10](https://cloud.githubusercontent.com/assets/718941/18056733/7e8f82c0-6e0d-11e6-9b0f-3f88796797d4.png)

![screen shot 2016-08-29 at 17 24 16](https://cloud.githubusercontent.com/assets/718941/18056735/864733a0-6e0d-11e6-9ed8-8a489cec582d.png)

I'll close this but feel free to open if I'm making a mistake.
