### ISSUE TITLE
Filters in mobile are broken

### ISSUE THREAD

**Issue by corroded** [davidpdrsn/CardistryIO#199]
<img width="351" alt="screen shot 2016-08-30 at 1 36 27 am" src="https://cloud.githubusercontent.com/assets/46548/18060686/36d75fa8-6e52-11e6-85ee-9f123e97fca0.png">

**Comment by davidpdrsn** [comment]
I believe @bendobos is gonna make lots of changes to the mobile version. So this will probably be fixed.

**Comment by bendobos** [comment]
I am aware of this. The whole mobile site is one huge WIP. Mobile is the next thing I'm gonna work on.

**Comment by corroded** [comment]
All good then!
