### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#2]
Lets discuss feature ideas here :smile:

---

Features we've agreed we will build:
- News feed with new stuff from your followers: New videos, new moves, private videos shared with you.
- Investigate uploading videos without leaving the site, through a 3rd party API such as YouTube.
- Update email, username, password
- Top lists of best videos and moves
- Some sort of filtering/searching of videos and moves
- Countries on users, and configure timezones.

---

Stuff thats done
- Ratings of moves and videos
- Comments, with editing
- Notifications on: New comments on your videos/moves, video approved
- Follow other users
- Notifications for new followers
- Credits on videos and moves
- Add types to videos such that they can be filtered etc
- Mentions
- Follow other users

**Comment by davidpdrsn** [comment]
So far my list contains:
- Different types of videos such as: Performance, tutorial, move showcase, idea.
- Some sort of notifications so you'll know when someone has commented on one of your things, or a video of yours have been approved.
- Rate videos and moves (done)
- From a move's page, specify which videos it appears in. Can right now only be done from a video's page.
- Specify credits for videos.
- Follow other users.
- News feed showing new things from the people you follow. 

Things for later:
- @mention people in comments, descriptions, etc.

**Comment by bendobos** [comment]
I agree with all of it. I'd say your list is the minimum feature-set for a beta release. Some more things I was thinking about:
- Newsstream: Should people be able to broadcast a message to their followers (à la Twitter), maybe even with a photo or video attached?
- Chatroom (maybe for later?): Public channels, private channels, video and audio support.
- "Report" and privacy features: A feature where people can report a post that is not wanted on our platform (spam, porn etc.). Privacy features are maybe for later but I think giving a user control about what others can see about him is important.

For later:
- Stylable profile pages (stuff like title images on Facebook for example)

Stuff already reflected in the UI:
- Notifications:
  <img width="73" alt="bildschirmfoto 2015-07-06 um 11 46 59" src="https://cloud.githubusercontent.com/assets/3368356/8519669/bbb6c80e-23d4-11e5-9125-8059e1b267a4.png">
  Lights up in red when a new notification arrived. A dropdown opens on click to show the news.
- Uploads:
  <img width="181" alt="bildschirmfoto 2015-07-06 um 11 47 39" src="https://cloud.githubusercontent.com/assets/3368356/8519688/d5479d0c-23d4-11e5-9d9d-5f46224b505b.png">
  The user clicks and a dropdown appears. User chooses what type of video he'd like to upload and gets redirected to the upload-screen. I'd say he'll have the opportunity to change the type of video there again, in case he did something wrong.
- News feed:
  <img width="916" alt="bildschirmfoto 2015-07-06 um 11 49 37" src="https://cloud.githubusercontent.com/assets/3368356/8519721/1d3dc834-23d5-11e5-8298-38d2cc987efc.png">
  A special kind of box for every type of submission. Has most important actions on it.

**Comment by bendobos** [comment]
Would it be an option for you to incorporate the "Ten Moves" functionality into CardistryIO? I think that way newer cardists who might not have a lot to show can benefit from the website's features as well.

I could also imagine sharing the progression graph if the user wants and things like that. We could also keep a "backlog" of what moves the user knows and how well he can do it.

**Comment by davidpdrsn** [comment]
First we should probably agree on when we would like to release the initial version. I'd say something around October should give us enough time. I've also talked with some people who would like to beta test so we should also have time enough for some iterations with the testers. And if we aim to release say October 31st that gives us 4 months, which should be more than enough. We can always move it close if things are going well. What do you think?

I think having a newsstream/feed is a great idea. I've built exactly this at work (however as a JSON API, but same same) so that shouldn't be too hard. I don't think its necessary to have Twitter like messages from the start but definitely updates about new videos, moves, etc. from the people you're following.

I doubt I'll be able to put together a chat room for the initial version. But thats definitely something I think we should have for a later release. Same goes for video chatting.

I also don't think its possible that users will be able to upload videos directly to the site in the initial version, only embed though YouTube, etc. Direct upload requires hosting which is expensive at scale :/ I don't think we should launch a feature like this before we are making money off of this in someway. Otherwise we'll just go bankrupt like Decknique did. But this is for sure something we should have at some point!

And several people have mentioned that some sort of integration with Ten Moves would be great. Not quite sure how it should work though. One way is that you could through the app, authorize with cardistry.io and then link your moves in the app to your moves on the website and have progress and stuff sync.
Another way would be to completely get rid of the app and build the features into the site instead.
Haven't thought much about this however.

I haven't thought much about privacy except that videos can be made private and then shared with select users.

And all the design things you've posted look really great! I think the feed is gonna look great when its full of awesome cardistry :smile:

I'll move notifications, follow users, and news feed to list of features we're agreed upon.

**Comment by bendobos** [comment]
4 months is a nice and generous time-frame. I like that! The beta phase is really necessary, I can also use that to evaluate the Usability of the site. I was also thinking about conducting a few user tests with people I know, just to be sure we get it right and even the most computer-hating cardist can upload his stuff.

The chat sure seems like something really complicated to build. Wouldn't we also need server resources for video chat?

To keep the flow consistent, I'd say it would be really cool if people don't need to leave the site to upload something. Couldn't we use the YouTube API to upload from CardistryIO to YouTube? (See https://developers.google.com/youtube/v3/guides/implementation/videos#videos-upload). If that would work, I'd say we never need our own storage.

The Ten Moves stuff was just an idea, I assume what you do with it is dependent on how much revenue the app generates for you? :dancers:

**Comment by davidpdrsn** [comment]
Alright then lets aim for October 31st as the initial release date. Its in my calendar :scream: 

Oh I did not think about using YouTube's API at all. I'll look into that!

Yeah I agree it would be best if people could upload stuff without jumping back and forth between different sites.

Video chat would probably require all kinds of advanced server stuff, never done anything like that.

**Comment by bendobos** [comment]
For video, I'm sure there are APIs and services making life easier for us. For example, I found this real quickly: https://tokbox.com.
I understand this is not our primary concern but I don't think it makes a lot of sense to build the technology again, from the ground up.

Edit: There's even a ruby gem for opentok: https://github.com/stijnster/opentok

**Comment by davidpdrsn** [comment]
I totally agree. I'll look the youtube API and see what else there is for hosting video somewhere else and when time comes to build video chat lets also investigate whats out there.

**Comment by davidpdrsn** [comment]
And now I've implemented ratings for moves and videos. I wanna talk with Kevin about bringing back the original rating texts that they had on Cheaters Cheater, in case he still remembers. Thought that would be a fun easter egg kinda thing :smile:

**Comment by davidpdrsn** [comment]
So today I added notifications, partially. For now you get notifications when someone comments on one of your videos. I'll add notifications for the following soon
- New video shared with you
- A video of yours have been approved
- Someone @mentions your username. I have no idea how to do this one, it'll be fun :smile: 

Once following is also in place I'll also add notifications for when new people follow you.

I've also completely removed first name and last name from users. Seemed overkill to have first name, last name, emails, and username. And first name, last name will make @mentions much harder, so we have to keep usernames

**Comment by davidpdrsn** [comment]
Comments can now be updated and it'll show a timestamp if a comment as been updated.

**Comment by davidpdrsn** [comment]
And now following should be working as well as notifications when someone follows you. I just followed you so you should have a notification waiting for you.

**Comment by davidpdrsn** [comment]
I now auto-detect mentions in
- Comments
- Move and video descriptions
- Notification texts

Let me know if I missed places where they should be detected.

At the moment you don't get notified when someone mentions you. I'll fix that tomorrow.

**Comment by bendobos** [comment]
So you found a way to make mentions work ;). Nice job!

**Comment by davidpdrsn** [comment]
And now its possible to add credits to moves and videos! With search as you type and everything.
Its only possible to credit people who are on the site at the moment and I say thats fine to begin with.

I've also added types to videos. So now you can choose between performance, tutorial, idea, move showcase, or other when adding a new video.

**Comment by davidpdrsn** [comment]
And now you get notifications when someone credits with a move or video.

**Comment by davidpdrsn** [comment]
I moved the remaining tasks to trello
