### ISSUE TITLE
Following/Unfollowing Ajax

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#218]
If you click follow or unfollow, we have a page reload at the moment. It'd be much cooler if this happened instantly without a reload.

Will keep my eyes peeled for more stuff where this would be better and edit it in here.
- Adding comments

**Comment by davidpdrsn** [comment]
Lets make separate issues for each idea. Will make it easier to keep track of much is left to do. I'll make one for comments.
