### ISSUE TITLE
Footer doesn't like long page

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#34]
![screen shot 2016-05-06 at 09 40 38](https://cloud.githubusercontent.com/assets/718941/15067156/a74bf77e-136e-11e6-8093-b9456e429744.png)

**Comment by davidpdrsn** [comment]
And here is a page with the error that you can also see http://cardistry.io/videos/1-waterwheel

**Comment by bendobos** [comment]
Oh nooo 😱😟
