### ISSUE TITLE
Should it be possible to edit or delete comments?

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#4]
It might be annoying if you make a comment with a typo and then you can't fix it. On the other hand its also bad if you reply to a comment and then the original comment gets edited or deleted.

What do you think?

I'm leaning to comments should be editable and deleteable, hopefully comments getting out of sync is uncommon. After all, Instagram allows it.

**Comment by davidpdrsn** [comment]
@bendobos

**Comment by bendobos** [comment]
I think as long as it is clearly marked that a comment was edited, it should be fine.

We should just watch how it goes as soon as we launched. If ninja-editing should become a problem, we should be able to implement counter-measures in no time.

**Comment by davidpdrsn** [comment]
Alright. I'll implement editing and show a timestamp if the comment was edited. Lets wait with delete and see if people complain.
