### ISSUE TITLE
Are ideas and moves the same thing?

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#45]
<img width="312" alt="screen shot 2016-05-06 at 10 16 48" src="https://cloud.githubusercontent.com/assets/718941/15067859/af4b8bc4-1373-11e6-9e5b-757601d4d4fe.png">

**Comment by bendobos** [comment]
I was thinking a move is something that is finished and polished and an idea is something you haven't put too much work into and need some feedback before you do.

**Comment by davidpdrsn** [comment]
Yep I agree. It'll be taken care of in https://github.com/davidpdrsn/CardistryIO/issues/97
