### ISSUE TITLE
Viewing the site on mobile devices

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#49]
If we go live at CC lots of people will be there checking the site on their phones, so we should aim to make the mobile experience great.

**Comment by bendobos** [comment]
I have already implemented a basic mobile layout in my branch, in case you haven't checked that out yet.
Will keep it updated and see that all the new screens work on mobile as well.

**Comment by davidpdrsn** [comment]
:+1:
