### ISSUE TITLE
Warnings from autoprefixer

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#69]
I noticed these warnings in the logs after updating "autoprefixer-rails"

```
web_1 | autoprefixer: /app/app/assets/stylesheets/application.css.scss:90:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
web_1 | autoprefixer: /app/app/assets/stylesheets/application.css.scss:374:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
web_1 | autoprefixer: /app/app/assets/stylesheets/application.css.scss:6237:3: You should write display: flex by final spec instead of display: box
```

**Comment by bendobos** [comment]
I'll have to check on that. It could be that this is because of a bourbon mixin. We use Bourbon at work too and get autoprefixer warnings with some of the mixins as well.
Are we on the latest version of Bourbon?

**Comment by davidpdrsn** [comment]
Yep we are at the latest version (4.2.7) but seems like they're preparing for 5.0. Lets revisit this at a late time. As long as everything works fine 😄
