### ISSUE TITLE
User Location

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#8]
Something that just crossed my mind:
Shouldn't we have an (optional) field for the user profile to input the country and/or city the live in.

**Comment by davidpdrsn** [comment]
Yeah would probably be a good idea.

I’ve also thought about adding a timezone to users. To localize times and dates.

**Comment by bendobos** [comment]
Ah! Nice thought!

If the user inputs his city anyways we could do this quite elegantly by using the [Google Geocode API](https://developers.google.com/maps/documentation/geocoding/?hl=de) to convert the city to latitude and longitude. Then there's the [Google Timezone API](https://developers.google.com/maps/documentation/timezone/) to get the timezone of specificed location. That way, the user doesn't have to input it manually (I, for one, HATE choosing my timezone). 

Only problem would be with users not wanting to disclose their location... However, I think the location (at least the country) should be mandatory, since this is also a pretty important part of a Cardistry social network I think.

**Comment by davidpdrsn** [comment]
Great idea! Using those APIs would basically kill two flies with one blow (or however say it).

It would also allow us to build features like "find nearby cardists" such that people could easily arrange meetups.

**Comment by bendobos** [comment]
Man, a feature like that would be AMAZING as soon as we've got enough users!

**Comment by davidpdrsn** [comment]
I'll add countries and timezone to the todo list
