### ISSUE TITLE
Video Responses

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#9]
If someone posts an idea (and makes it public), wouldn't it be cool if other users could post a "video response" in which they can show how they are working with the posted idea?

**Comment by davidpdrsn** [comment]
Moved to trello https://trello.com/c/DmoWA5VC/5-if-someone-posts-an-idea-and-makes-it-public-wouldn-t-it-be-cool-if-other-users-could-post-a-video-response-in-which-they-can-sh
